export const SITE = {
  name: "Danish Aqib",
  role: "Full Stack Engineer & AI Specialist",
  location: "Islamabad, Pakistan",
  timezone: "PKT (UTC+5)",
  email: "danishaqib129@gmail.com",
  github: "github.com/DanishAqib",
  linkedin: "linkedin.com/in/danishaqib",
  fiverr: "https://www.fiverr.com/s/e6Gol1j",
  available: true,
  availabilityNote: "Available for new projects",
  tagline: "I turn complex business processes into software that runs itself.",
  bio: [
    "I'm a full-stack engineer who builds things that solve real business problems — not just things that look nice in a Figma file. For 4+ years I've shipped production web apps, two-sided marketplaces, and AI-powered platforms for international clients across the US, UK, Germany, Canada, and beyond.",
    "My specialty is the messy middle: the 'we do this manually in a spreadsheet' problem. I pick it up, integrate the right AI tools (OpenAI, Claude, Gemini), and hand back something your team actually uses. I've watched manual workloads drop by 70% on projects I've shipped. I communicate clearly, deliver on time, and I'm still reachable months after launch.",
  ],
  stats: [
    { num: "4", unit: "+", lbl: "Years Delivering" },
    { num: "15", unit: "K+", lbl: "Users on Live Apps" },
    { num: "70", unit: "%", lbl: "Ops Automated" },
    { num: "12", unit: "+", lbl: "Production Apps" },
  ],
};

export const PROJECTS = [
  {
    id: "rounddance",
    name: "Rounddance",
    category: "Commerce Platform",
    year: "2024",
    tag: "A marketplace connecting 15,000+ Indigenous-owned businesses with consumers across North America. Full commerce stack with payments, seller dashboards, and geolocation.",
    outcome: "15,000+ businesses onboarded across North America",
    metric: { big: "15K+", small: "businesses" },
    stack: ["Next.js", "Node.js", "PostgreSQL", "AWS", "Stripe"],
    image: "/images/proj-rounddance.png",
    link: "https://rounddance.co",
    color: "#c0392b",
  },
  {
    id: "sportsops",
    name: "Sports Ops",
    category: "AI Operations Dashboard",
    year: "2025",
    tag: "Multi-group operations platform where a Telegram bot captures incoming messages and screenshots, then Claude parses them into structured dashboard data via AI vision. CSV imports use AI-assisted field mapping, a review/approval queue handles edge cases, and Supabase Realtime streams live P&L and profit-split updates across all widgets — no page refreshes.",
    metric: { big: "Real-time", small: "AI pipeline" },
    stack: ["Next.js", "Supabase", "Claude", "Telegram Bot API", "Vercel"],
    image: "/images/proj-sportsops.png",
    link: null,
    note: "Private client dashboard",
    color: "#2563eb",
  },
  {
    id: "crewforge",
    name: "Crewforge",
    category: "Talent Marketplace",
    year: "2024",
    tag: "Two-sided marketplace pairing film and TV crew with production companies. Tiered subscriptions, real-time job alerts, calendar-based availability tracking.",
    outcome: "Two-sided marketplace live in production",
    metric: { big: "2-sided", small: "marketplace" },
    stack: ["Next.js", "Supabase", "Firebase", "Stripe", "Vercel"],
    image: "/images/proj-crewforge.png",
    link: "https://crewforge.pro",
    color: "#f39c12",
  },
  {
    id: "bair",
    name: "BAIR",
    category: "AI EdTech Platform",
    year: "2024",
    tag: "AI SaaS automating lesson plans, quizzes, and educational content for one of Pakistan's largest school networks. Teachers stopped spending Sundays on prep work.",
    outcome: "70% reduction in manual content creation",
    metric: { big: "70%", small: "less manual work" },
    stack: ["React", "Flask", "OpenAI", "Google Workspace", "MySQL"],
    image: null,
    video: "/images/bair-demo.mp4",
    link: null,
    note: "Internal platform — demo available on request",
    color: "#8e44ad",
  },
  {
    id: "nowhow",
    name: "Nowhow.ai",
    category: "B2B AI Platform",
    year: "2024",
    tag: "Connects industry experts, IT solution providers, and SMEs through AI-powered matchmaking. Multi-role auth, admin dashboard, content moderation engine.",
    outcome: "AI matchmaking live across three user tiers",
    metric: { big: "AI", small: "matchmaking" },
    stack: ["Next.js", "Node.js", "OpenAI", "PostgreSQL", "Tailwind"],
    image: "/images/proj-nowhow.png",
    link: "https://nowhow.ai",
    color: "#e67e22",
  },
  {
    id: "drinkx",
    name: "Drink-X",
    category: "Social Discovery App",
    year: "2023",
    tag: "Discover, review, and share beverages. Geolocation bar finder, crowdsourced ratings, dual consumer and business interface with Google Maps integration.",
    outcome: "Live social platform with geo + ratings engine",
    metric: { big: "Geo", small: "+ social" },
    stack: ["Vue.js", "Flask", "PostgreSQL", "AWS", "Google Maps"],
    image: "/images/proj-drinkx.png",
    link: "https://drink-x.com",
    color: "#16a085",
  },
];

export const SERVICES = [
  {
    num: "01",
    title: "Full-Stack Web Apps",
    body: "From landing page to full product. React or Next.js on the front, Node or Python on the back, Postgres or Supabase underneath. You describe the outcome — I build it and ship it.",
    tags: ["Web Apps", "SaaS", "Dashboards"],
  },
  {
    num: "02",
    title: "AI Automation",
    body: "Plug OpenAI, Claude, or Gemini into your existing workflow. Document generation, intelligent chatbots, automated pipelines — the stuff that makes your team stop doing things they hate.",
    tags: ["OpenAI", "Claude", "Automations"],
  },
  {
    num: "03",
    title: "Marketplaces & SaaS",
    body: "Two-sided marketplaces, subscription models, Stripe payments, admin dashboards. I've shipped this pattern enough times to have strong opinions about what breaks and what doesn't.",
    tags: ["Marketplaces", "Stripe", "Multi-role"],
  },
];

export const TESTIMONIALS = [
  {
    name: "fnordshopper",
    country: "United Kingdom",
    flag: "🇬🇧",
    gig: "Custom Websites + AI",
    text: "Danish is my go-to web developer — excellent service and has built me some amazing websites. Integrated ChatGPT into it and it works great. Will be using again.",
    stars: 5,
  },
  {
    name: "user48980118",
    country: "Germany",
    flag: "🇩🇪",
    gig: "Custom Websites",
    text: "Our company from Germany always turns to Danish because he always works on time and meticulously takes care of every detail. We are more than impressed with his skills!",
    stars: 5,
  },
  {
    name: "bdsherman4069",
    country: "United States",
    flag: "🇺🇸",
    gig: "Custom Websites",
    text: "I really appreciate Danish and his work ethic, level of expertise, and willingness to learn and integrate new things. He went above and beyond my expectations.",
    stars: 5,
  },
  {
    name: "linkinmo",
    country: "Spain",
    flag: "🇪🇸",
    gig: "Custom Websites",
    text: "Danish did an excellent job on the first milestone of our platform — clean auth system with multi-role logic, profile setup, and responsive design, all perfectly aligned with our roadmap.",
    stars: 5,
  },
  {
    name: "reg_123de",
    country: "Germany",
    flag: "🇩🇪",
    gig: "AI Integrations",
    text: "Several developers rejected my project because of difficulties but Danish didn't. He built a Python script connecting my site to ChatGPT so I could answer messages automatically. Very helpful support!",
    stars: 5,
  },
  {
    name: "byeranby",
    country: "Israel",
    flag: "🇮🇱",
    gig: "AI Integrations",
    text: "The service provider was attentive, held several Zoom meetings with me, and worked on the product until it came out well and to my satisfaction. Definitely recommend.",
    stars: 5,
  },
  {
    name: "aman_28022",
    country: "United Kingdom",
    flag: "🇬🇧",
    gig: "Custom Websites",
    text: "Cannot recommend or thank Danish enough — he has been exceptional and extremely prompt!",
    stars: 5,
  },
  {
    name: "milleshus",
    country: "Denmark",
    flag: "🇩🇰",
    gig: "Custom Websites",
    text: "Amazing result yet again, great communication and exceeded expectations. Thanks a lot and see you soon!",
    stars: 5,
  },
  {
    name: "hatimali",
    country: "Morocco",
    flag: "🇲🇦",
    gig: "AI Integrations",
    text: "Working with this seller was a fantastic experience! He demonstrated exceptional expertise, met all deadlines, and communicated effectively. Highly recommended!",
    stars: 5,
  },
  {
    name: "haris_shabeer01",
    country: "Pakistan",
    flag: "🇵🇰",
    gig: "Custom Websites",
    text: "Excellent work quality — I am very happy with the final results. Fully recommend. Five stars is not enough, thanks for your quality and very quick work.",
    stars: 5,
  },
  {
    name: "fabiopnz",
    country: "New Zealand",
    flag: "🇳🇿",
    gig: "Custom Websites",
    text: "Great result for what I asked. Danish delivered in a professional and friendly manner.",
    stars: 5,
  },
  {
    name: "magoonic",
    country: "United Kingdom",
    flag: "🇬🇧",
    gig: "Custom Websites",
    text: "Great communication and delivered exactly what was promised. I would recommend!",
    stars: 5,
  },
];
